using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using KnifeHero.KnifeHeroCode.Character;
using KnifeHero.KnifeHeroCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;

namespace KnifeHero.KnifeHeroCode.Cards;

/* Shiv — a thrown-knife token (CardTag.Shiv, a Blade). 0-cost, deal 4 to ALL enemies, Exhaust +
   Ethereal (a knife you throw THIS turn or lose). Generated by Superfan of Knives; Token rarity so
   it never appears as a reward. */
public sealed class Shiv() : KnifeHeroCard(0, CardType.Attack, CardRarity.Token, TargetType.AllEnemies), IBlade
{
    public override IEnumerable<CardKeyword> CanonicalKeywords =>
        new List<CardKeyword> { CardKeyword.Exhaust, CardKeyword.Ethereal };

    protected override HashSet<CardTag> CanonicalTags => new() { CardTag.Shiv };

    protected override IEnumerable<DynamicVar> CanonicalVars =>
        new List<DynamicVar> { new DamageVar(4m, ValueProp.Move) };

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await DamageCmd.Attack(DynamicVars.Damage.BaseValue).FromCard(this).TargetingAllOpponents(CombatState)
            .WithHitFx("vfx/vfx_attack_slash").Execute(choiceContext);
    }
}
