#!/usr/bin/env python3
"""cards.py — regenerate CARDS_IMPLEMENTED.md from source. Ground truth, cannot drift.

    ./tools/cards.py            # write CARDS_IMPLEMENTED.md
    ./tools/cards.py --check    # exit 1 if the file is stale (for CI / pre-commit)

Reads the actual card classes out of KnifeHeroCode/ and the actual card text out of
KnifeHero/localization/eng/cards.json, and joins them. If a card is in source but has no
loc, or has loc but no class, that is REPORTED, not hidden — those are the two ways a card
silently half-exists.

Why this exists: CARDS.md was hand-maintained and went a month stale (2026-06-13 snapshot vs
54 cards actually in source). A hand-written list of what's implemented will always drift from
what's implemented. This one is derived, so it can't.

CARDS.md stays as Hallie's DESIGN doc — prose, intent, open threads, not-yet-built cards.
This file is only "what is actually compiled right now."
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "CARDS_IMPLEMENTED.md"
LOC = ROOT / "KnifeHero/localization/eng/cards.json"

# class Foo() : KnifeHeroCard(1, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy)
CARD_RE = re.compile(
    r"class\s+(\w+)\(\)\s*:\s*(KnifeHeroCard|CreatureCard|PrideCard)\("
    r"\s*(-?\d+)\s*,\s*CardType\.(\w+)\s*,\s*CardRarity\.(\w+)\s*,\s*TargetType\.(\w+)"
)
KEYWORD_RE = re.compile(r"CardKeyword\.(\w+)")
IFACE_RE = re.compile(r"class\s+\w+\(\)\s*:\s*(?:KnifeHeroCard|CreatureCard)\([^)]*\)\s*,\s*([\w\s,]+)")


def snake(name: str) -> str:
    """ButchBlade -> BUTCH_BLADE (matches the loc key convention)."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def main() -> int:
    loc = json.loads(LOC.read_text())
    cards = []
    seen_files = {}

    for cs in sorted(ROOT.glob("KnifeHeroCode/**/*.cs")):
        text = cs.read_text(encoding="utf-8", errors="replace")
        # split into per-class chunks so keywords attach to the right card
        for m in CARD_RE.finditer(text):
            name, base, cost, ctype, rarity, target = m.groups()
            chunk = text[m.start(): m.start() + 2000]
            kws = sorted(set(KEYWORD_RE.findall(chunk)))
            im = IFACE_RE.search(text[m.start(): m.start() + 400])
            ifaces = [i.strip() for i in im.group(1).split(",")] if im else []
            ifaces = [i for i in ifaces if i.startswith("I")]
            key = f"KNIFEHERO-{snake(name)}"
            cards.append({
                "name": name, "base": base, "cost": int(cost), "type": ctype,
                "rarity": rarity, "target": target, "keywords": kws, "ifaces": ifaces,
                "title": loc.get(f"{key}.title"), "text": loc.get(f"{key}.description"),
                "file": str(cs.relative_to(ROOT)),
            })
            seen_files[key] = cs.name

    # loc keys with no class behind them
    loc_titles = {k[:-6] for k in loc if k.endswith(".title")}
    orphan_loc = sorted(loc_titles - set(seen_files))

    def fmt_cost(c: int) -> str:
        return "—" if c < 0 else str(c)

    lines = [
        "# Knife Hero — IMPLEMENTED cards (generated)",
        "",
        "> **Generated by `./tools/cards.py` — do not hand-edit; your edits will be overwritten.**",
        "> This is only *what is actually compiled right now*, joined from the card classes in",
        "> `KnifeHeroCode/` and the card text in `localization/eng/cards.json`.",
        ">",
        "> **For design — intent, open threads, cards not yet built — edit [`CARDS.md`](CARDS.md).**",
        "> That's the human doc. This one is the mirror.",
        "",
    ]

    for base, label in (("KnifeHeroCard", "THE GAY BLADE"), ("CreatureCard", "THE CREATURE")):
        group = [c for c in cards if c["base"] == base]
        lines += [f"## {label}  ({len(group)} cards)", ""]
        for ctype in ("Basic", "Attack", "Skill", "Power", "Status", "Curse"):
            sub = [c for c in group if c["type"] == ctype or c["rarity"] == ctype]
            sub = [c for c in sub if not (ctype != "Basic" and c["rarity"] == "Basic")]
            if not sub:
                continue
            lines += [f"### {ctype}", "", "| card | ⟨cost⟩ | rarity | text | keywords | tags |", "|---|---|---|---|---|---|"]
            for c in sorted(sub, key=lambda x: x["name"]):
                title = c["title"] or f"**⚠ NO LOC** ({c['name']})"
                text = (c["text"] or "⚠ **no card text**").replace("\n", " ")
                kws = ", ".join(c["keywords"]) or "—"
                tags = ", ".join(c["ifaces"]) or "—"
                lines.append(f"| **{title}** | {fmt_cost(c['cost'])} | {c['rarity']} | {text} | {kws} | {tags} |")
            lines.append("")

    lines += ["---", "", "## Integrity", ""]
    no_loc = [c["name"] for c in cards if not c["title"]]
    lines.append(f"- **{len(cards)} card classes** in source ({sum(1 for c in cards if c['base'] == 'KnifeHeroCard')} Gay Blade, "
                 f"{sum(1 for c in cards if c['base'] == 'CreatureCard')} Creature).")
    lines.append(f"- Cards in source with **no localization**: {', '.join(no_loc) if no_loc else 'none ✅'}")
    lines.append(f"- Localization keys with **no card class**: {', '.join(o.replace('KNIFEHERO-', '') for o in orphan_loc) if orphan_loc else 'none ✅'}")
    lines.append("")
    body = "\n".join(lines)

    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != body:
            print("CARDS_IMPLEMENTED.md is STALE — run ./tools/cards.py", file=sys.stderr)
            return 1
        print("CARDS_IMPLEMENTED.md is current ✅")
        return 0

    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(ROOT)} — {len(cards)} cards")
    if no_loc:
        print(f"  ⚠ {len(no_loc)} card(s) with no loc: {', '.join(no_loc)}")
    if orphan_loc:
        print(f"  ⚠ {len(orphan_loc)} loc key(s) with no class: {', '.join(orphan_loc)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
